daemon: false
verbosity: 2

plugins:
  ubuntu-vuln:
    source: ghcr.io/compliance-framework/plugin-os-ubuntu:latest
    policies:
      - ghcr.io/compliance-framework/plugin-os-ubuntu-policies:latest
    labels:
      type: ubuntu-vuln
      group: private
      owner: auth-api
