#!/bin/bash

COMPOSE_COMMAND="${COMPOSE_COMMAND:-podman-compose}"
CWD=$(pwd)

start_common() {
    ${COMPOSE_COMMAND} -f ${CWD}/compose/common.yml -f ${CWD}/compose/ui.yml up -d
}

start_api() {
    ${COMPOSE_COMMAND} -f ${CWD}/compose/common.yml -f ${CWD}/compose/api.yml -f ${CWD}/compose/ui.yml up -d
}

start_agents() {
    ${COMPOSE_COMMAND} -f ${CWD}/compose/common.yml -f ${CWD}/compose/demo-agents.yml up -d
}

start_all() {
    ${COMPOSE_COMMAND} -f ${CWD}/compose/common.yml -f ${CWD}/compose/api.yml -f ${CWD}/compose/ui.yml -f ${CWD}/compose/demo-agents.yml up -d
}

stop() {
    ${COMPOSE_COMMAND} -f ${CWD}/compose/common.yml -f ${CWD}/compose/api.yml -f ${CWD}/compose/ui.yml -f ${CWD}/compose/demo-agents.yml down
}

destroy() {
    ${COMPOSE_COMMAND} -f ${CWD}/compose/common.yml -f ${CWD}/compose/api.yml -f ${CWD}/compose/ui.yml -f ${CWD}/compose/demo-agents.yml down -v
}

pull() {
    ${COMPOSE_COMMAND} -f ${CWD}/compose/common.yml -f ${CWD}/compose/api.yml -f ${CWD}/compose/ui.yml -f ${CWD}/compose/demo-agents.yml pull
}

build() {
    ${COMPOSE_COMMAND} -f ${CWD}/compose/common.yml -f ${CWD}/compose/api.yml -f ${CWD}/compose/ui.yml -f ${CWD}/compose/demo-agents.yml build
}

# Run is the default function. No need to call its name.
run() {
    ${COMPOSE_COMMAND} -f ${CWD}/compose/common.yml -f ${CWD}/compose/api.yml -f ${CWD}/compose/ui.yml -f ${CWD}/compose/demo-agents.yml "$@"
}


# Check if the function exists
if declare -f "$1" > /dev/null
then
  # call arguments verbatim
  "$@"
else
  # Run a command against all
  run "$@"
fi
