apiVersion: v1
kind: Secret
metadata:
  name: azure-secrets
type: Opaque
data:
  client-id: {{ .Values.assessmentRuntime.env.azureClientId | b64enc | quote }}
  client-secret: {{ .Values.assessmentRuntime.env.azureClientSecret | b64enc | quote }}
  tenant-id: {{ .Values.assessmentRuntime.env.azureTenantId | b64enc | quote }}
