version: "3"

services:

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    volumes:
      - .nats-server.conf:/etc/nats/nats-server.conf
    networks:
      - continuous-compliance

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    networks:
      - continuous-compliance

  configuration-service:
    image: ghcr.io/compliance-framework/configuration-service:latest
    ports:
      - "8080:8080"
    environment:
      NATS_URI: nats://nats:4222
      MONGO_URI: mongodb://mongo:27017

volumes:
  mongo:

networks:
  continuous-compliance:
