daemon: false
verbosity: 2

api:
  url: http://configuration-service:8080

plugins:
  ssh:
    source: ghcr.io/compliance-framework/plugin-local-ssh:v0.1.1
    policies:
      - ghcr.io/compliance-framework/plugin-local-ssh-policies:latest
    labels:
      group: public
      owner: sales-api

  apt-versions:
    source: ghcr.io/compliance-framework/plugin-apt-versions:v0.3.0
    policies:
      - ghcr.io/compliance-framework/plugin-apt-versions-policies:latest
    labels:
      group: public
      owner: sales-api
