daemon: false
verbosity: 2

api:
  url: http://configuration-service:8080

plugins:
  ssh:
    source: ghcr.io/compliance-framework/plugin-local-ssh:v0.0.14
    policies:
      - ghcr.io/compliance-framework/plugin-local-ssh-policies:latest
    labels:
      group: private
      owner: auth-api
