apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-proxy-reader-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: ccf
roleRef:
  kind: ClusterRole
  name: node-proxy-reader
  apiGroup: rbac.authorization.k8s.io
