apiVersion: v1
kind: ConfigMap
metadata:
  name: plugin-kubernetes-policies-config
data:
  config.yaml: |
    daemon: true
    verbosity: 2

    api:
      url: http://host.minikube.internal:8080

    plugins:
      pod:
        source: ghcr.io/compliance-framework/plugin-kubernetes-pod:v0.0.1
        policies:
          - ghcr.io/compliance-framework/plugin-kubernetes-pod-policies:latest
        labels:
          type: k8s
          service: pod
      cluster:
        source: ghcr.io/compliance-framework/plugin-kubernetes-cluster:v0.0.4
        policies:
          - ghcr.io/compliance-framework/plugin-kubernetes-cluster-policies:latest
        labels:
          type: k8s
          service: RBAC-etc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plugin-kubernetes
  labels:
    app: plugin-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plugin-kubernetes
  template:
    metadata:
      labels:
        app: plugin-kubernetes
    spec:
      terminationGracePeriodSeconds: 600
      containers:
        - name: compliance-agent
          image: ghcr.io/compliance-framework/agent:latest
          command: ["/app/concom"]
          args: ["agent", "-c", "/app/.compliance-framework/config.yaml"]
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          volumeMounts:
            - name: config-volume
              mountPath: "/app/.compliance-framework/config.yaml"
              subPath: "config.yaml"
      volumes:
        - name: config-volume
          configMap:
            name: plugin-kubernetes-policies-config
