services:
  configuration-service:
    image: ghcr.io/compliance-framework/configuration-service:0.1.4
    ports:
      - "8080:8080"
    volumes:
      - ./api.env:/.env
    networks:
      - continuous-compliance
    environment:
      MONGO_URI: mongodb://mongo:27017
