services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    volumes:
      - ../nats-server.conf:/etc/nats/nats-server.conf
    networks:
      - continuous-compliance

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    networks:
      - continuous-compliance

volumes:
  mongo:

networks:
  continuous-compliance:
