services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    networks:
      - continuous-compliance

volumes:
  mongo:

networks:
  continuous-compliance:
