services:
  worker-1:
    build:
      context: ../demo-agents/ubuntu
      args:
        AGENT_VERSION: 0.0.13
    image: demo-agent:latest
    hostname: kube-prod-worker-1
    volumes:
      - ../demo-agents/versions/composite/config-1.yml:/config.yml
    networks:
      - continuous-compliance

  worker-2:
    build:
      context: ../demo-agents/ubuntu
      args:
        AGENT_VERSION: 0.0.13
    image: demo-agent:latest
    hostname: kube-prod-worker-2
    volumes:
      - ../demo-agents/versions/composite/config-2.yml:/config.yml
    networks:
      - continuous-compliance

  worker-3:
    build:
      context: ../demo-agents/ubuntu
      args:
        AGENT_VERSION: 0.0.13
    image: demo-agent:latest
    hostname: kube-prod-worker-3
    volumes:
      - ../demo-agents/versions/composite/config-3.yml:/config.yml
    networks:
      - continuous-compliance

  worker-4:
    build:
      context: ../demo-agents/ubuntu
      args:
        AGENT_VERSION: 0.0.13
    image: demo-agent:latest
    hostname: kube-prod-worker-4
    volumes:
      - ../demo-agents/versions/composite/config-4.yml:/config.yml
    networks:
      - continuous-compliance

  server-1:
    build:
      context: ../demo-agents/apt-versions
      args:
        AGENT_VERSION: 0.0.13
    hostname: server-ubuntu-2018-1
    volumes:
      - ../demo-agents/versions/apt-versions/config-1.yml:/config.yml
    networks:
      - continuous-compliance
