services:
  worker-1:
    build:
      context: ../demo-agents/ubuntu
      args:
        AGENT_VERSION: 0.1.6
    image: demo-agent:0.1.6
    hostname: kube-prod-worker-1
    volumes:
      - ../demo-agents/versions/composite/config-1.yml:/config.yml
    env_file: "../.env"
    networks:
      - continuous-compliance

  worker-2:
    build:
      context: ../demo-agents/ubuntu
      args:
        AGENT_VERSION: 0.1.6
    image: demo-agent:0.1.6
    hostname: kube-prod-worker-2
    volumes:
      - ../demo-agents/versions/composite/config-2.yml:/config.yml
    env_file: "../.env"
    networks:
      - continuous-compliance

  worker-3:
    build:
      context: ../demo-agents/ubuntu
      args:
        AGENT_VERSION: 0.1.6
    image: demo-agent:0.1.6
    hostname: kube-prod-worker-3
    volumes:
      - ../demo-agents/versions/composite/config-3.yml:/config.yml
    env_file: "../.env"
    networks:
      - continuous-compliance

  worker-4:
    build:
      context: ../demo-agents/ubuntu
      args:
        AGENT_VERSION: 0.1.6
    image: demo-agent:0.1.6
    hostname: kube-prod-worker-4
    volumes:
      - ../demo-agents/versions/composite/config-4.yml:/config.yml
    env_file: "../.env"
    networks:
      - continuous-compliance

  # This worker requires AWS env vars
  worker-aws:
    build:
      context: ../demo-agents/ubuntu
      args:
        AGENT_VERSION: 0.1.6
    image: demo-agent:0.1.6
    hostname: aws-worker-1
    volumes:
      - ../demo-agents/versions/aws/config.yml:/config.yml
    env_file: "../.env"
    networks:
      - continuous-compliance


  # This worker requires Azure env vars
  worker-azure:
    build:
      context: ../demo-agents/azure
      args:
        AGENT_VERSION: 0.1.6
    image: demo-agent:0.1.6
    hostname: azure-worker-1
    volumes:
      - ../demo-agents/versions/azure/config.yml:/config.yml
    env_file: "../.env"
    networks:
      - continuous-compliance

  server-1:
    build:
      context: ../demo-agents/apt-versions
      args:
        AGENT_VERSION: 0.1.6
    image: server-agent:0.1.6
    hostname: server-ubuntu-2018-1
    volumes:
      - ../demo-agents/versions/apt-versions/config-1.yml:/config.yml
    env_file: "../.env"
    networks:
      - continuous-compliance
