services:
  worker-1:
    build: 
      context: ../demo-agents/ubuntu
    hostname: kube-prod-worker-1
    volumes:
      - ../demo-agents/versions/composite/config-1.yml:/config.yml
    networks:
      - continuous-compliance

  worker-2:
    build:
      context: ../demo-agents/ubuntu
    hostname: kube-prod-worker-2
    volumes:
      - ../demo-agents/versions/composite/config-2.yml:/config.yml
    networks:
      - continuous-compliance

  worker-3:
    build:
      context: ../demo-agents/ubuntu
    hostname: kube-prod-worker-3
    volumes:
      - ../demo-agents/versions/composite/config-3.yml:/config.yml
    networks:
      - continuous-compliance

  worker-4:
    build:
      context: ../demo-agents/ubuntu
    hostname: kube-prod-worker-4
    volumes:
      - ../demo-agents/versions/composite/config-4.yml:/config.yml
    networks:
      - continuous-compliance
