daemon: false
verbosity: 2

api:
  url: http://configuration-service:8080

plugins:
  apt-versions:
    source: ghcr.io/compliance-framework/plugin-apt-versions:v0.2.6
    policies:
      - ghcr.io/compliance-framework/plugin-apt-versions-policies:latest
    labels:
      type: apt-versions
      group: public
      owner: auth-api
