daemon: false
verbosity: 2

nats:
  url: nats://nats:4222

plugins:
  apt-versions:
    source: ghcr.io/compliance-framework/plugin-apt-versions:latest
    policies:
      - ghcr.io/compliance-framework/plugin-apt-versions-policies:latest
    labels:
      type: apt-versions
      group: private
      owner: auth-api
