daemon: false
verbosity: 2

nats:
  url: nats://nats:4222

plugins:
  local-ssh-check:
    source: ghcr.io/compliance-framework/plugin-local-ssh:latest
    policies:
      - ghcr.io/compliance-framework/plugin-local-ssh-policies:latest
    assessment-plan-ids:
      - 675c415e1bef9f6936adb9b8
